(() => {
"use strict";
const S={progress:"dr.progress.v1",profile:"dr.profile.v1",reviews:"dr.reviews.v1",activity:"dr.activity.v1",tests:"dr.tests.v1",theme:"dr.theme.v1"};
const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}};
const state={data:null,quizzes:null,view:"dashboard",level:"A1",practiceFilter:"الكل",done:new Set(read(S.progress,[])),profile:Object.assign({dailyMinutes:210,currentLevel:"A1"},read(S.profile,{})),reviews:read(S.reviews,{}),activity:read(S.activity,[]),tests:read(S.tests,[])};
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const E={nav:$$(".nav-btn"),views:$$(".view"),theme:$("#themeToggle"),daily:$("#dailyMinutes"),overallPct:$("#overallPct"),overallDone:$("#overallDone"),ring:$("#overallRing"),currentLevel:$("#currentLevelStat"),next:$("#nextLessonStat"),due:$("#dueStat"),streak:$("#streakStat"),todayTitle:$("#todayTitle"),todayTime:$("#todayTime"),todayPlan:$("#todayPlan"),skillBars:$("#skillBars"),coachTitle:$("#coachTitle"),coachText:$("#coachText"),startToday:$("#startToday"),goNext:$("#goNextLesson"),levelTabs:$("#levelTabs"),levelSummary:$("#levelSummary"),modules:$("#modules"),practiceFilters:$("#practiceFilters"),practiceGrid:$("#practiceGrid"),levelTestTitle:$("#levelTestTitle"),levelTestBtn:$("#levelTestBtn"),quizBox:$("#quizBox"),testHistory:$("#testHistory"),reset:$("#resetAll")};
const save=()=>{localStorage.setItem(S.progress,JSON.stringify([...state.done]));localStorage.setItem(S.profile,JSON.stringify(state.profile));localStorage.setItem(S.reviews,JSON.stringify(state.reviews));localStorage.setItem(S.activity,JSON.stringify(state.activity));localStorage.setItem(S.tests,JSON.stringify(state.tests))};
const level=()=>state.data.levels.find(l=>l.id===state.profile.currentLevel)||state.data.levels[0];
const keyLesson=(lid,x)=>"L::"+lid+"::"+x.id, keyResource=(lid,x)=>"R::"+lid+"::"+x.id;
const todayKey=(d=new Date())=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
function touch(){const t=todayKey();if(!state.activity.includes(t))state.activity.push(t);state.activity=[...new Set(state.activity)].sort().slice(-500)}
function streak(){const s=new Set(state.activity);let d=new Date();if(!s.has(todayKey(d))){d.setDate(d.getDate()-1);if(!s.has(todayKey(d)))return 0}let n=0;while(s.has(todayKey(d))){n++;d.setDate(d.getDate()-1)}return n}
function setReview(k,grade="good"){const days={hard:1,good:3,easy:7}[grade]||3;state.reviews[k]={grade,last:Date.now(),due:Date.now()+days*86400000};touch();save()}
function mark(k){if(state.done.has(k)){state.done.delete(k);delete state.reviews[k]}else{state.done.add(k);setReview(k,"good")}save();renderAll()}
function dueItems(){const now=Date.now(),out=[];for(const l of state.data.levels){for(const x of l.lessons){const k=keyLesson(l.id,x);if(state.done.has(k)&&state.reviews[k]?.due<=now)out.push({k,lid:l.id,item:x,type:"lesson"})}for(const x of l.resources){const k=keyResource(l.id,x);if(state.done.has(k)&&state.reviews[k]?.due<=now)out.push({k,lid:l.id,item:x,type:"resource"})}}return out.sort((a,b)=>state.reviews[a.k].due-state.reviews[b.k].due)}
function allItems(l){return [...l.lessons.map(x=>({k:keyLesson(l.id,x),skill:x.skill,item:x,type:"lesson"})),...l.resources.map(x=>({k:keyResource(l.id,x),skill:x.skill,item:x,type:"resource"}))]}
function estimate(x,t){if(t==="review")return 15;if(x.minutes)return x.minutes;if(t==="resource")return x.skill==="الكتابة"?30:x.skill==="اختبار"?40:25;return x.kind==="listening"?30:x.kind==="pronunciation"?25:40}
function skillStats(l){const m={};for(const e of allItems(l)){m[e.skill]??={total:0,done:0};m[e.skill].total++;if(state.done.has(e.k))m[e.skill].done++}return Object.entries(m).map(([skill,v])=>({skill,...v,pct:Math.round(v.done/v.total*100)})).sort((a,b)=>a.pct-b.pct)}
function nextLesson(l){return l.lessons.find(x=>!state.done.has(keyLesson(l.id,x)))}
function buildPlan(){const l=level(),target=+state.profile.dailyMinutes,tasks=[],used=new Set();let mins=0;for(const r of dueItems().filter(x=>x.lid===l.id).slice(0,2)){const m=15;tasks.push({...r,planType:"review",minutes:m});used.add(r.k);mins+=m}const n=nextLesson(l);if(n){const k=keyLesson(l.id,n),m=estimate(n,"lesson");tasks.push({k,lid:l.id,item:n,type:"lesson",planType:"lesson",minutes:m});used.add(k);mins+=m}const weak=skillStats(l).map(x=>x.skill);const pool=l.resources.map(x=>({k:keyResource(l.id,x),lid:l.id,item:x,type:"resource",planType:"resource",minutes:estimate(x,"resource"),skill:x.skill})).filter(x=>!state.done.has(x.k)).sort((a,b)=>weak.indexOf(a.skill)-weak.indexOf(b.skill));for(const p of pool){if(tasks.length>=5)break;if(mins+p.minutes>target+20&&tasks.length>=2)continue;tasks.push(p);mins+=p.minutes;if(mins>=target*.75)break}return {tasks,mins,target}}
function showView(id){state.view=id;E.views.forEach(v=>v.classList.toggle("active",v.id===id));E.nav.forEach(b=>b.classList.toggle("active",b.dataset.view===id));scrollTo({top:0,behavior:"smooth"})}
function renderDash(){const l=level(),all=state.data.levels.flatMap(allItems),done=all.filter(x=>state.done.has(x.k)).length,p=Math.round(done/all.length*100),n=nextLesson(l),due=dueItems().filter(x=>x.lid===l.id);E.overallPct.textContent=p+"%";E.overallDone.textContent=done;E.ring.style.background="conic-gradient(var(--accent) "+(p*3.6)+"deg,var(--surface2) 0)";E.currentLevel.textContent=l.id;E.next.textContent=n?"درس "+String(n.order).padStart(2,"0"):"مكتمل";E.due.textContent=due.length;E.streak.textContent=streak()+" يوم";const plan=buildPlan();E.todayTitle.textContent="خطة "+l.id+" لليوم";E.todayTime.textContent=plan.mins+" / "+plan.target+" دقيقة";E.todayPlan.innerHTML="";if(!plan.tasks.length){E.todayPlan.innerHTML='<p class="muted">كملت عناصر هذا المستوى الحالية. دير اختبار المستوى ثم انتقل للمستوى التالي.</p>'}else plan.tasks.forEach((t,i)=>{const row=document.createElement("article");row.className="task";const label=t.planType==="review"?"مراجعة":t.planType==="lesson"?"درس":"تطبيق "+t.item.skill;row.innerHTML='<div class="task-index">'+(i+1)+'</div><div><strong>'+t.item.title+'</strong><small>'+label+' • ≈ '+t.minutes+' دقيقة</small></div><div><a href="'+t.item.url+'" target="_blank" rel="noopener">ابدأ</a>'+(t.planType==="review"?'<button data-review="'+t.k+'" data-grade="good">راجعت</button>':'')+'</div>';E.todayPlan.appendChild(row)});E.todayPlan.querySelectorAll("[data-review]").forEach(b=>b.onclick=()=>{setReview(b.dataset.review,b.dataset.grade);renderAll()});const ss=skillStats(l);E.skillBars.innerHTML=ss.map(s=>'<div class="skill-row"><div><span>'+s.skill+'</span><strong>'+s.pct+'%</strong></div><div class="bar"><i style="width:'+s.pct+'%"></i></div></div>').join("");const weak=ss[0];if(done===0){E.coachTitle.textContent="ابدأ بالدرس 01";E.coachText.textContent="أولاً نبني بيانات حقيقية عن تقدمك. أكمل الدروس وقيّم المراجعات، وبعدها الخطة تتغير تلقائياً."}else if(weak){E.coachTitle.textContent="أقل مهارة تدربت عليها: "+weak.skill;E.coachText.textContent="تغطيتها "+weak.pct+"%. هذا يقيس التدريب داخل الموقع، وليس حكماً نهائياً على قدرتك اللغوية."}}
function renderPath(){E.levelTabs.innerHTML=state.data.levels.map(l=>'<button class="level-tab '+(l.id===state.profile.currentLevel?"active":"")+'" data-level="'+l.id+'">'+l.id+'</button>').join("");E.levelTabs.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{state.profile.currentLevel=b.dataset.level;save();renderAll()});const l=level(),items=allItems(l),done=items.filter(x=>state.done.has(x.k)).length,p=Math.round(done/items.length*100);E.levelSummary.innerHTML='<div class="section-head"><div><p class="eyebrow">'+l.id+' • '+l.label+'</p><h2>'+l.title+'</h2><p class="muted">'+l.goal+'</p></div></div><div class="level-summary-grid"><div><span>الوحدات</span><strong>'+l.modules.length+'</strong></div><div><span>الفيديوهات</span><strong>'+l.lessons.length+'</strong></div><div><span>الموارد</span><strong>'+l.resources.length+'</strong></div><div><span>الإنجاز</span><strong>'+p+'%</strong></div></div>';E.modules.innerHTML="";for(const m of l.modules){const lessons=l.lessons.filter(x=>x.module===m.id),mdone=lessons.filter(x=>state.done.has(keyLesson(l.id,x))).length;const box=document.createElement("article");box.className="module";box.innerHTML='<div class="module-head"><div class="module-no">'+String(m.order).padStart(2,"0")+'</div><div><h3>'+m.title+'</h3><p>'+m.goal+'</p></div><span class="module-progress">'+mdone+'/'+lessons.length+'</span></div><div class="lesson-list"></div>';const list=box.querySelector(".lesson-list");for(const x of lessons){const k=keyLesson(l.id,x),d=state.done.has(k),row=document.createElement("div");row.className="lesson"+(d?" done":"");row.innerHTML='<div class="lesson-num">'+String(x.order).padStart(2,"0")+'</div><div><h4>'+x.title+'</h4><p>'+x.note+'</p><div class="lesson-meta"><span>'+x.provider+'</span><span>'+x.skill+'</span><span>≈ '+estimate(x,"lesson")+'د</span></div></div><div class="lesson-actions"><a href="'+x.url+'" target="_blank" rel="noopener">فيديو</a><button data-key="'+k+'">'+(d?"✓ مكتمل":"تم")+'</button></div>';list.appendChild(row)}list.querySelectorAll("[data-key]").forEach(b=>b.onclick=()=>mark(b.dataset.key));E.modules.appendChild(box)}}
function renderPractice(){const l=level(),skills=["الكل",...new Set(l.resources.map(r=>r.skill))];E.practiceFilters.innerHTML=skills.map(s=>'<button class="filter '+(s===state.practiceFilter?"active":"")+'" data-filter="'+s+'">'+s+'</button>').join("");E.practiceFilters.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.practiceFilter=b.dataset.filter;renderPractice()});const list=l.resources.filter(r=>state.practiceFilter==="الكل"||r.skill===state.practiceFilter);E.practiceGrid.innerHTML=list.map(r=>'<article class="resource"><div class="meta"><span>'+r.provider+'</span><span>'+r.skill+'</span></div><h3>'+r.title+'</h3><p>'+r.note+'</p><a href="'+r.url+'" target="_blank" rel="noopener">فتح المورد</a></article>').join("")}
function renderHistory(){E.testHistory.innerHTML='<div class="section-head"><div><p class="eyebrow">السجل</p><h2>نتائج الاختبارات</h2></div></div>'+(state.tests.length?state.tests.slice().reverse().map(x=>'<div class="history-item"><strong>'+x.name+'</strong><span>'+x.score+'/'+x.total+' • '+x.pct+'% • '+x.date+'</span></div>').join(""):'<p class="muted">ما درتي حتى اختبار بعد.</p>')}
function runTest(id){const q=state.quizzes[id];if(!q)return;const answers={};E.quizBox.classList.remove("hidden");E.quizBox.innerHTML='<div class="section-head"><div><p class="eyebrow">Quiz</p><h2>'+q.title+'</h2></div><span class="pill">'+q.questions.length+' أسئلة</span></div><div id="questions"></div><button id="submitQuiz" class="primary-btn" type="button">صحح الاختبار</button>';const qb=E.quizBox.querySelector("#questions");q.questions.forEach((x,i)=>{const row=document.createElement("div");row.className="quiz-q";row.innerHTML='<strong>'+(i+1)+'. '+x.q+'</strong><div class="answers">'+x.options.map((o,j)=>'<button type="button" class="answer" data-q="'+i+'" data-a="'+j+'">'+o+'</button>').join("")+'</div>';qb.appendChild(row)});qb.querySelectorAll(".answer").forEach(b=>b.onclick=()=>{answers[b.dataset.q]=+b.dataset.a;b.parentElement.querySelectorAll(".answer").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});E.quizBox.querySelector("#submitQuiz").onclick=()=>{let score=0;q.questions.forEach((x,i)=>{if(answers[i]===x.answer)score++});const pct=Math.round(score/q.questions.length*100);state.tests.push({id,name:q.title,score,total:q.questions.length,pct,date:todayKey()});if(id==="placement"){state.profile.currentLevel=pct>=80?"B2":pct>=60?"B1":pct>=35?"A2":"A1"}save();E.quizBox.innerHTML='<p class="eyebrow">النتيجة</p><h2>'+pct+'%</h2><p class="muted">جاوبت صحيح على '+score+' من '+q.questions.length+'. '+(id==="placement"?"تم تحديث المستوى المقترح إلى "+state.profile.currentLevel+".":"استعمل النتيجة لمعرفة واش خاصك مراجعة إضافية.")+'</p><button class="secondary-btn" id="closeQuiz">إغلاق</button>';E.quizBox.querySelector("#closeQuiz").onclick=()=>{E.quizBox.classList.add("hidden");renderAll()};renderHistory()}}
function renderTests(){E.levelTestTitle.textContent="اختبار "+state.profile.currentLevel;renderHistory()}
function renderAll(){renderDash();renderPath();renderPractice();renderTests()}
E.nav.forEach(b=>b.onclick=()=>showView(b.dataset.view));E.theme.onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;localStorage.setItem(S.theme,t);E.theme.textContent=t==="dark"?"☀":"☾"};E.daily.onchange=()=>{state.profile.dailyMinutes=+E.daily.value;save();renderDash()};E.startToday.onclick=()=>E.todayPlan.scrollIntoView({behavior:"smooth",block:"center"});E.goNext.onclick=()=>{showView("path");setTimeout(()=>E.modules.querySelector(".lesson:not(.done)")?.scrollIntoView({behavior:"smooth",block:"center"}),100)};E.levelTestBtn.onclick=()=>runTest(state.profile.currentLevel);$$("[data-test]").forEach(b=>b.onclick=()=>runTest(b.dataset.test));E.reset.onclick=()=>{if(confirm("مسح كل التقدم والاختبارات والمراجعات؟")){Object.values(S).forEach(k=>localStorage.removeItem(k));location.reload()}};
Promise.all([fetch("./data/curriculum.json").then(r=>r.json()),fetch("./data/quizzes.json").then(r=>r.json())]).then(([data,quizzes])=>{state.data=data;state.quizzes=quizzes;E.daily.value=String(state.profile.dailyMinutes);document.documentElement.dataset.theme=localStorage.getItem(S.theme)||"dark";E.theme.textContent=document.documentElement.dataset.theme==="dark"?"☀":"☾";renderAll()}).catch(err=>{console.error(err);document.body.insertAdjacentHTML("beforeend",'<div style="padding:20px">تعذر تحميل بيانات المشروع.</div>')});
})();