"use client";
import { FormEvent, useState } from "react";

type Score={overall:number;accuracy:number;fluency:number;completeness:number;feedbackAr:string[]};
export function PronunciationLab(){
  const target="Ich möchte einen Kaffee, bitte."; const [transcript,setTranscript]=useState(""); const [score,setScore]=useState<Score>(); const [busy,setBusy]=useState(false);
  function speak(){if(!("speechSynthesis" in window))return;const u=new SpeechSynthesisUtterance(target);u.lang="de-DE";u.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(u)}
  async function submit(e:FormEvent){e.preventDefault();if(!transcript.trim())return;setBusy(true);try{const r=await fetch("/api/speech/score-pronunciation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({target,transcript})});setScore(await r.json())}finally{setBusy(false)}}
  return <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><form onSubmit={submit} className="glass rounded-2xl p-6"><p className="text-xs font-black text-blue-600">AUSSPRACHE LAB</p><h2 className="mt-3 text-2xl font-black" dir="ltr">{target}</h2><button type="button" onClick={speak} className="mt-4 rounded-xl border px-4 py-3 font-bold">🔊 اسمع النطق المرجعي</button><label className="mt-6 block text-sm font-bold">النص الذي التقطه Speech Recognition أو ما قلته<input value={transcript} onChange={e=>setTranscript(e.target.value)} className="mt-2 w-full rounded-xl border bg-transparent px-4 py-3" dir="ltr" placeholder="Ich möchte einen Kaffee, bitte."/></label><button disabled={busy||!transcript.trim()} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 font-black text-white disabled:opacity-40">{busy?"يتم التقييم...":"قيّم النطق"}</button><p className="muted mt-3 text-xs">في Mock Mode نقيس دقة الـtranscript واكتمال الجملة. عند ربط مزود صوت يمكن إضافة phoneme alignment والتحليل الطيفي.</p></form><aside className="glass rounded-2xl p-5"><h3 className="font-black">النتيجة</h3>{score?<div className="mt-4 space-y-4"><div className="text-center text-5xl font-black text-blue-600">{score.overall}</div>{[["الدقة",score.accuracy],["الطلاقة",score.fluency],["الاكتمال",score.completeness]].map(([k,v])=><div key={String(k)}><div className="flex justify-between text-sm"><span>{k}</span><span>{v}%</span></div><div className="mt-1 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-blue-600" style={{width:`${v}%`}}/></div></div>)}<ul className="list-disc space-y-2 pr-5 text-sm">{score.feedbackAr.map(x=><li key={x}>{x}</li>)}</ul></div>:<p className="muted mt-4 text-sm">أدخل transcript ثم اضغط التقييم.</p>}</aside></div>
}
