"use client";
import { useState } from "react";

const transcript="Entschuldigung, fährt dieser Zug nach Berlin? Ja, aber Sie müssen in Hannover umsteigen.";
export function ListeningLab(){
  const [speed,setSpeed]=useState(.9);const [show,setShow]=useState(false);const [answer,setAnswer]=useState<string>();
  function play(){if(!("speechSynthesis" in window))return;const u=new SpeechSynthesisUtterance(transcript);u.lang="de-DE";u.rate=speed;speechSynthesis.cancel();speechSynthesis.speak(u)}
  return <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><section className="glass rounded-2xl p-6"><p className="text-xs font-black text-blue-600">HÖREN · A1</p><h2 className="mt-2 text-2xl font-black">Am Bahnhof</h2><div className="mt-5 flex flex-wrap items-center gap-3"><button onClick={play} className="rounded-xl bg-blue-600 px-5 py-3 font-black text-white">▶ استمع</button><label className="text-sm font-bold">السرعة <select value={speed} onChange={e=>setSpeed(Number(e.target.value))} className="mr-2 rounded-lg border bg-transparent px-2 py-2"><option value={.7}>0.7×</option><option value={.9}>0.9×</option><option value={1}>1×</option><option value={1.15}>1.15×</option></select></label><button onClick={()=>setShow(v=>!v)} className="rounded-xl border px-4 py-3 font-bold">{show?"أخفِ النص":"أظهر النص"}</button></div>{show&&<p className="mt-5 rounded-xl bg-slate-50 p-4 text-lg leading-8 dark:bg-slate-900" dir="ltr">{transcript}</p>}<div className="mt-6 border-t pt-5"><p className="font-black">Wo muss die Person umsteigen?</p><div className="mt-3 flex gap-2">{["Berlin","Hannover","Hamburg"].map(x=><button key={x} onClick={()=>setAnswer(x)} className={`rounded-xl border px-4 py-2 ${answer===x?"border-blue-600 bg-blue-50":""}`}>{x}</button>)}</div>{answer&&<p className={`mt-3 font-bold ${answer==="Hannover"?"text-emerald-600":"text-red-600"}`}>{answer==="Hannover"?"Richtig ✓":"اسمع المقطع مرة أخرى."}</p>}</div></section><aside className="glass rounded-2xl p-5"><h3 className="font-black">طريقة 3 Pass</h3><ol className="mt-4 list-decimal space-y-3 pr-5 text-sm leading-6"><li>استمع دون نص وافهم الفكرة.</li><li>استمع مع Transcript وحدد ما فاتك.</li><li>شغّل مرة أخرى وردد خلف الصوت.</li></ol></aside></div>
}
