"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function RegisterForm(){
  const router=useRouter();
  const[fullName,setFullName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[targetLevel,setTargetLevel]=useState("B1");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const res=await fetch("/api/auth/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fullName,email,password,targetLevel})});const data=await res.json();if(!res.ok){setMessage(data.error??"تعذر إنشاء الحساب");return}if(data.needsEmailVerification){setMessage("أنشئ الحساب. تحقق من بريدك الإلكتروني قبل تسجيل الدخول.");return}setMessage(data.mode==="mock"?"تم إنشاء حساب تجريبي في Mock Mode.":"تم إنشاء الحساب بنجاح.");setTimeout(()=>router.push("/dashboard"),400)}catch{setMessage("تعذر الاتصال بالخادم.")}finally{setBusy(false)}}
  return <form onSubmit={submit} className="mt-6 grid gap-4"><label className="font-bold">الاسم<input value={fullName} onChange={e=>setFullName(e.target.value)} autoComplete="name" className="mt-1 w-full rounded-xl border bg-transparent p-3" required minLength={2}/></label><label className="font-bold">البريد<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" className="mt-1 w-full rounded-xl border bg-transparent p-3" required/></label><label className="font-bold">كلمة المرور<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="new-password" minLength={8} className="mt-1 w-full rounded-xl border bg-transparent p-3" required/></label><label className="font-bold">الهدف<select value={targetLevel} onChange={e=>setTargetLevel(e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-3"><option>A1</option><option>A2</option><option>B1</option><option>B2</option></select></label><button disabled={busy} className="rounded-xl bg-blue-600 p-3 font-bold text-white disabled:opacity-50">{busy?"جارٍ الإنشاء...":"إنشاء الحساب"}</button>{message&&<p className="rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-900" aria-live="polite">{message}</p>}</form>
}
